### ISSUE TITLE
Update Readme and Timeline

### ISSUE THREAD

**Issue by emreozdil** [emreozdil/Swift-Daily-Tips#92]

**Comment by jobinsjohn** [comment]
What are the updates that you want to do?

**Comment by emreozdil** [comment]
> What are the updates that you want to do?

According to [Twitter](https://twitter.com/SwiftDailyTips) add tips to the readme file and timeline.
In Readme; 57, 58 ... tips should be added.
In Timeline 43, 44 ... tips should be added.
